### ISSUE TITLE
How to import only the issues of a particular milestone from github?

### ISSUE THREAD

**Issue by simkimsia** [linear/linear-import#43]
I like to import github open isssues one milestone at a time. How to do that?

**Comment by rlargman** [comment]
@simkimsia We don't currently have the option to import GitHub open issues by milestone. We don't have plans to add this functionality, but if you would like to do so, feel free to open a pull request! The GitHub GraphQL API does support fetching milestones from a given repository: https://docs.github.com/en/graphql/reference/objects#repository
