### ISSUE TITLE
Installing with npm fails if yarn isn't installed as well

### ISSUE THREAD

**Issue by filipecatraia** [linear/linear-import#50]
Hey Linear,

I just tried to do a fresh install via `npm i -g @linear/import`, but it failed after installation because you've hard-coded the build process with `yarn build`. Systems without yarn therefore fail at that step.

Just a FYI, not a biggie :)

**Comment by rlargman** [comment]
@filipecatraia This issue should be fixed now. Do you still have this problem?

**Comment by filipecatraia** [comment]
I haven't had the chance to try it, so I would mark it closed for the moment :)
