### ISSUE TITLE
Error: Cannot find module '../dist'

### ISSUE THREAD

**Issue by ajshortt** [linear/linear-import#56]
Tried installing on both NPM and Yarn, hitting the same issues both times. Am I being stupid here???

**OS:** macOS 11.1 - **Node:** v12.16.2 (via NVM) - **NPM:** 7.5.4 
![Screenshot 2021-02-22 at 11 19 21](https://user-images.githubusercontent.com/6783995/108701630-1c4a1900-7500-11eb-9f6b-723323b663f2.jpg)

**Comment by rubikzube** [comment]
Just encountered the same thing ... reverting to 0.2.3 (pre-10 days ago) helped

**Comment by littlemooon** [comment]
Hey @ajshortt, nope, you're not being stupid 😂

We are in the process of transferring this package into our new monorepo https://github.com/linear/linear

I have published an update that runs successfully for me.

Please update to @linear/import@1.4.8 and let me know if you hit any further issues!

**Comment by ajshortt** [comment]
Thanks @littlemooon. Superb response time.
