### ISSUE TITLE
Impossible to preserve CreatedAt date during import

### ISSUE THREAD

**Issue by firemuzzy** [linear/linear-import#67]
Am trying to migrate my Asana tickets into linear but there is no way to migrate the CreatedAt date making all the old bugs be listed as created on the import date.

Steps done:

- Updated `AsanaCsvImporter.ts` to extract `createdAt` from asana csv
- tried adding `createdAt` date to `mutation createIssue(` in `importIssues.ts` however `IssueCreateInput` does not have a createdAt date so I get a ` Field "createdAt" is not defined by type "IssueCreateInput"` error

Is it in any way possible to migrate the createdAt date. 
Loosing the created date is a big blocker to our migration.

**Comment by rlargman** [comment]
@firemuzzy Have you tried our built in Asana importer? It is under Settings > Import/Export. That should preserve created dates for you. A example below:

<img width="600" alt="Screen Shot 2021-09-13 at 11 45 07 AM" src="https://user-images.githubusercontent.com/4577711/133139377-1bf7513d-bc02-4a26-ba90-c530ec67e926.png">

Let me know if you have problems with that

**Comment by firemuzzy** [comment]
@rlargman I tried it last week. And it looks like it got stuck. Nothing was imported and the previous import keeps showing "processing"

![image](https://user-images.githubusercontent.com/1335910/133139825-dfe8c32f-8c3b-4636-9a66-6289450f5719.png)

Just tried the import again into another team. It detects the issue counts and lets me select their assignment but nothing happens afterwards

![image](https://user-images.githubusercontent.com/1335910/133140576-10a2bf54-4af3-4907-bf20-f97bb12c975e.png)


Thanks for the quick response

**Comment by firemuzzy** [comment]
I have screen recording videos attached to some of the Asana bugs and those files are each anywhere from 5MB to 15MB, could that cause an import issue?

**Comment by firemuzzy** [comment]
@rlargman the second import just went through, any ideas how the first one got stuck?

**Comment by rlargman** [comment]
@firemuzzy Not sure how the first one got stuck without being able to identify the specific import. Could you join our [Slack community](http://linear.app/join-slack) and DM me the name of the organization where you did these imports, or send a support message (command + k --> type Help & support --> select contact us) about the imports so I can look into the errors?
